import {
  EXPLORER_URLS,
  GET_LOGO_URL,
  GET_RESOURCES_LIST_URL,
  GET_STELLAR_TOKEN_LIST_URL,
  NATIVE_ADDRESS,
  RPC,
  RPC_URLS,
} from './constants';
import { type IChain } from './types';

export const ETH = {
  RPC: RPC.ETHRPC,
  chainId: 1,
  nativeChainKey: 'ethereum',
  minGasGwei: 10,
  imageUrl: GET_LOGO_URL('eth'),
  name: 'Ethereum',
  symbol: 'ETH',
  rangoSymbol: 'ETH',
  chainName: 'Ethereum',
  subName: 'Mainnet',
  gasLimit: 65000,
  bridgeSupportTokens: [
    {
      name: 'Tether USD',
      symbol: 'USDT',
      address: '0xdAC17F958D2ee523a2206206994597C13D831ec7',
      chainId: 1,
      decimals: 6,
      logoURI:
        'https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0xdAC17F958D2ee523a2206206994597C13D831ec7/logo.png',
    },
    {
      name: 'USD Coin',
      symbol: 'USDC',
      address: '0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48',
      chainId: 1,
      decimals: 6,
      logoURI:
        'https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48/logo.png',
    },
  ],
};

export const ARB = {
  RPC: RPC.ARBRPC,
  chainId: 42161,
  nativeChainKey: 'arbitrum-one',
  minGasGwei: 0.1,
  imageUrl: GET_LOGO_URL('arb'),
  name: 'Arbitrum One',
  // Chain identifier symbol (used for chain selection UI)
  symbol: 'ARB',
  rangoSymbol: 'ARBITRUM',
  chainName: 'Arbitrum',
  subName: 'L2',
  gasLimit: 65000,
  // The actual gas token on Arbitrum is ETH (not the ARB governance token)
  nativeGasToken: {
    symbol: 'ETH',
    name: 'Ether',
    decimals: 18,
    logoURI:
      'https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/info/logo.png',
  },
  bridgeSupportTokens: [
    {
      name: 'Tether USD',
      symbol: 'USDT',
      address: '0xFd086bC7CD5C481DCC9C85ebE478A1C0b69FCbb9',
      chainId: 42161,
      decimals: 6,
      logoURI:
        'https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0xdAC17F958D2ee523a2206206994597C13D831ec7/logo.png',
    },
    {
      name: 'USD Coin',
      symbol: 'USDC',
      address: '0xaf88d065e77c8cC2239327C5EDb3A432268e5831',
      chainId: 42161,
      decimals: 6,
      logoURI:
        'https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48/logo.png',
    },
  ],
};

export const POL = {
  RPC: RPC.POLRPC,
  chainId: 137,
  nativeChainKey: 'polygon-pos',
  minGasGwei: 30,
  imageUrl: GET_LOGO_URL('poly'),
  name: 'Polygon',
  symbol: 'POL',
  rangoSymbol: 'POLYGON',
  chainName: 'Polygon',
  subName: 'POS',
  gasLimit: 65000,
  bridgeSupportTokens: [
    {
      name: 'Tether USD',
      symbol: 'USDT',
      address: '0xc2132D05D31c914a87C6611C10748AEb04B58e8F',
      chainId: 137,
      decimals: 6,
      logoURI:
        'https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0xdAC17F958D2ee523a2206206994597C13D831ec7/logo.png',
    },
    {
      name: 'USD Coin',
      symbol: 'USDC',
      address: '0x3c499c542cEF5E3811e1192ce70d8cC03d5c3359',
      chainId: 137,
      decimals: 6,
      logoURI:
        'https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48/logo.png',
    },
  ],
};

export const OPT = {
  RPC: RPC.OPRPC,
  chainId: 10,
  nativeChainKey: 'optimistic-ethereum',
  minGasGwei: 0.001,
  imageUrl: GET_LOGO_URL('op'),
  name: 'Optimism',
  // Chain identifier symbol
  symbol: 'OPT',
  rangoSymbol: 'OPTIMISM',
  chainName: 'Optimism',
  subName: 'L2',
  gasLimit: 65000,
  // The actual gas token on Optimism is ETH
  nativeGasToken: {
    symbol: 'ETH',
    name: 'Ether',
    decimals: 18,
    logoURI:
      'https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/info/logo.png',
  },
  bridgeSupportTokens: [
    {
      name: 'Tether USD',
      symbol: 'USDT',
      address: '0x94b008aA00579c1307B0EF2c499aD98a8ce58e58',
      chainId: 10,
      decimals: 6,
      logoURI:
        'https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0xdAC17F958D2ee523a2206206994597C13D831ec7/logo.png',
    },
    {
      name: 'USD Coin',
      symbol: 'USDC',
      address: '0x0b2C639c533813f4Aa9D7837CAf62653d097Ff85',
      chainId: 10,
      decimals: 6,
      logoURI:
        'https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48/logo.png',
    },
  ],
};

export const AVAX = {
  RPC: RPC.AVAXRPC,
  chainId: 43114,
  nativeChainKey: 'avalanche',
  minGasGwei: 25,
  imageUrl: GET_LOGO_URL('avax'),
  name: 'Avalanche',
  symbol: 'AVAX',
  rangoSymbol: 'AVAX_CCHAIN',
  chainName: 'Avalanche',
  subName: 'C-Chain',
  gasLimit: 65000,
  bridgeSupportTokens: [
    {
      name: 'Tether USD',
      symbol: 'USDT',
      address: '0x9702230A8Ea53601f5cD2dc00fDBc13d4df4A8c7',
      chainId: 43114,
      decimals: 6,
      logoURI:
        'https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0xdAC17F958D2ee523a2206206994597C13D831ec7/logo.png',
    },
    {
      name: 'USD Coin',
      symbol: 'USDC',
      address: '0xB97EF9Ef8734C71904D8002F8b6Bc66Dd9c48a6E',
      chainId: 43114,
      decimals: 6,
      logoURI:
        'https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48/logo.png',
    },
  ],
};

export const BASE = {
  RPC: RPC.BASERPC,
  chainId: 8453,
  nativeChainKey: 'base',
  minGasGwei: 0.001,
  imageUrl: GET_LOGO_URL('base'),
  name: 'Base',
  // Chain identifier symbol
  symbol: 'BASE',
  rangoSymbol: 'BASE',
  chainName: 'Base',
  subName: 'L2',
  gasLimit: 65000,
  // The actual gas token on Base is ETH
  nativeGasToken: {
    symbol: 'ETH',
    name: 'Ether',
    decimals: 18,
    logoURI:
      'https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/info/logo.png',
  },
  bridgeSupportTokens: [
    {
      name: 'Tether USD',
      symbol: 'USDT',
      address: '0xfde4C96c8593536E31F229EA8f37b2ADa2699bb2',
      chainId: 8453,
      decimals: 6,
      logoURI:
        'https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0xdAC17F958D2ee523a2206206994597C13D831ec7/logo.png',
    },
    {
      name: 'USD Coin',
      symbol: 'USDC',
      address: '0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913',
      chainId: 8453,
      decimals: 6,
      logoURI:
        'https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48/logo.png',
    },
  ],
};

export const BSC = {
  RPC: RPC.BSCRPC,
  chainId: 56,
  nativeChainKey: 'bnbMainnet',
  minGasGwei: 1,
  imageUrl: 'https://coin-images.coingecko.com/coins/images/825/large/bnb-icon2_2x.png?1696501970',
  name: 'Binance',
  symbol: 'BNB',
  rangoSymbol: 'BSC',
  chainName: 'BSC',
  subName: 'BNB',
  gasLimit: 65000,
  bridgeSupportTokens: [
    {
      name: 'Binance USDT',
      symbol: 'USDT',
      address: '0x55d398326f99059fF775485246999027B3197955',
      chainId: 56,
      decimals: 18,
      logoURI:
        'https://tokens.pancakeswap.finance/images/0x55d398326f99059fF775485246999027B3197955.png',
    },
    {
      name: 'Binance USDC',
      symbol: 'USDC',
      address: '0x8AC76a51cc950d9822D68b83fE1Ad97B32Cd580d',
      chainId: 56,
      decimals: 18,
      logoURI:
        'https://tokens.pancakeswap.finance/images/0x8AC76a51cc950d9822D68b83fE1Ad97B32Cd580d.png',
    },
  ],
};

export const STR = {
  RPC: RPC.STRRPC,
  chainId: 'pubnet',
  nativeChainKey: 'stellar',
  minGasGwei: 100,
  imageUrl:
    'https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/stellar/info/logo.png',
  name: 'Stellar',
  symbol: 'SRB',
  chainName: 'Stellar',
  subName: 'Network',
  bridgeSupportTokens: [
    {
      name: 'USD Coin',
      symbol: 'USDC',
      address: 'GA5ZSEJYB37JRC5AVCIA5MOP4RHTM335X2KGX3IHOJAPP5RE34K4KZVN',
      chainId: 'pubnet',
      decimals: 7,
      logoURI:
        'https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48/logo.png',
    },
    {
      name: 'Stellar',
      symbol: 'XLM',
      address: 'native',
      chainId: 'pubnet',
      decimals: 7,
      logoURI:
        'https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/stellar/info/logo.png',
    },
  ],
};

export const STR_TESTNET = {
  RPC: RPC.STRRPC_TESTNET,
  chainId: 'testnet',
  nativeChainKey: 'stellar',
  minGasGwei: 100,
  imageUrl:
    'https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/stellar/info/logo.png',
  name: 'Stellar',
  symbol: 'SRB',
  chainName: 'Stellar',
  subName: 'Testnet',
  bridgeSupportTokens: [
    {
      name: 'Stellar Lumens',
      symbol: 'XLM',
      address: 'native',
      chainId: 'testnet',
      decimals: 7,
      logoURI:
        'https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/stellar/info/logo.png',
    },
    {
      name: 'USD Coin (Testnet)',
      symbol: 'USDC',
      address: 'GBBD47IF6LWK7P7MDEVSCWR7DPUWV3NY3DTQEVFL4NAT4AQH3ZLLFLA5',
      chainId: 'testnet',
      decimals: 7,
      logoURI:
        'https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48/logo.png',
    },
    {
      name: 'Euro Coin (Testnet)',
      symbol: 'EURC',
      address: 'GACD5TONLCRLWT2EOSQLSK5D6CFJMQSWO6PIP5VF6B73UVCKRSYIMXTY',
      chainId: 'testnet',
      decimals: 7,
      logoURI:
        'https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0x1aBaEA1f7C830bD89Acc67eC4af516284b1bC33c/logo.png',
    },
    {
      name: 'Aqua (Testnet)',
      symbol: 'AQUA',
      address: 'GAO2UQT2N7NGSHLNNS5AUGEEEOU3BXER6GGIYFJBF5OUNCLVONUYT3PS',
      chainId: 'testnet',
      decimals: 7,
      logoURI: 'https://aqua.network/assets/img/aqua-logo.png',
    },
    {
      name: 'SwiftEx Token (Testnet)',
      symbol: 'SWIFT',
      address: 'GBVAJRR3O24B3TULTXH5HP4HGADXMORIEEOEWZAKUQFUZETT64NRF5LI',
      chainId: 'testnet',
      decimals: 7,
      logoURI: '/logo.png',
    },
    {
      name: 'Wrapped Bitcoin (Testnet)',
      symbol: 'WBTC',
      address: 'GAXAMPQXMVMRZPZNZEHIAVXO5PXL5VYXOWRRB3SCERPPDLZKUKHV6ZRZ',
      chainId: 'testnet',
      decimals: 7,
      logoURI:
        'https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0x2260FAC5E5542a773Aa44fBCfeDf7C193bc2C599/logo.png',
    },
    {
      name: 'Wrapped Ether (Testnet)',
      symbol: 'WETH',
      address: 'GBWDY7L6YMM4TAX4RSPX4NMDSFMIX7PQLYKYCTXZH76EIVMPSRJ2CKM4',
      chainId: 'testnet',
      decimals: 7,
      logoURI:
        'https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2/logo.png',
    },
    {
      name: 'ACME Token (Testnet)',
      symbol: 'ACME',
      address: 'GB75GYGNXJ566NKBMDUBMKGZQWWNLYAT3FWSMCPX3O3427JGQ3D3CC33',
      chainId: 'testnet',
      decimals: 7,
      logoURI:
        'https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/stellar/info/logo.png',
    },
  ],
};

// ---------------------------------------------------------------------------
// EVM Testnet Chains
// ---------------------------------------------------------------------------

export const SEPOLIA = {
  RPC: RPC.SEPOLIARPC,
  chainId: 11155111,
  nativeChainKey: 'ethereum-sepolia',
  minGasGwei: 1,
  imageUrl: GET_LOGO_URL('eth'),
  name: 'Ethereum Sepolia',
  symbol: 'ETH',
  chainName: 'Ethereum',
  subName: 'Sepolia Testnet',
  bridgeSupportTokens: [
    {
      name: 'Test USDC (Sepolia)',
      symbol: 'USDC',
      address: '0x1c7D4B196Cb0C7B01d743Fbc6116a902379C7238',
      chainId: 11155111,
      decimals: 6,
      logoURI:
        'https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48/logo.png',
    },
  ],
};

export const BSC_TESTNET_CHAIN = {
  RPC: RPC.BSC_TESTNETRPC,
  chainId: 97,
  nativeChainKey: 'binance-testnet',
  minGasGwei: 10,
  imageUrl: GET_LOGO_URL('bsc'),
  name: 'BNB Testnet',
  symbol: 'BSC',
  chainName: 'BNB Smart Chain',
  subName: 'Testnet',
  bridgeSupportTokens: [],
};

export const AMOY = {
  RPC: RPC.AMOYRPC,
  chainId: 80002,
  nativeChainKey: 'polygon-amoy',
  minGasGwei: 1,
  imageUrl: GET_LOGO_URL('poly'),
  name: 'Polygon Amoy',
  symbol: 'POL',
  chainName: 'Polygon',
  subName: 'Amoy Testnet',
  bridgeSupportTokens: [],
};

export const ARB_SEPOLIA = {
  RPC: RPC.ARB_SEPOLIARPC,
  chainId: 421614,
  nativeChainKey: 'arbitrum-sepolia',
  minGasGwei: 0.1,
  imageUrl: GET_LOGO_URL('arb'),
  name: 'Arbitrum Sepolia',
  symbol: 'ARB',
  chainName: 'Arbitrum',
  subName: 'Sepolia Testnet',
  bridgeSupportTokens: [],
};

export const OPT_SEPOLIA = {
  RPC: RPC.OPT_SEPOLIARPC,
  chainId: 11155420,
  nativeChainKey: 'optimism-sepolia',
  minGasGwei: 0.001,
  imageUrl: GET_LOGO_URL('op'),
  name: 'Optimism Sepolia',
  symbol: 'OPT',
  chainName: 'Optimism',
  subName: 'Sepolia Testnet',
  bridgeSupportTokens: [],
};

export const BASE_SEPOLIA = {
  RPC: RPC.BASE_SEPOLIARPC,
  chainId: 84532,
  nativeChainKey: 'base-sepolia',
  minGasGwei: 0.001,
  imageUrl: GET_LOGO_URL('base'),
  name: 'Base Sepolia',
  symbol: 'BASE',
  chainName: 'Base',
  subName: 'Sepolia Testnet',
  bridgeSupportTokens: [],
};

export const AVAX_FUJI = {
  RPC: RPC.AVAX_FUJIRPC,
  chainId: 43113,
  nativeChainKey: 'avalanche-fuji',
  minGasGwei: 25,
  imageUrl: GET_LOGO_URL('avax'),
  name: 'Avalanche Fuji',
  symbol: 'AVAX',
  chainName: 'Avalanche',
  subName: 'Fuji Testnet',
  bridgeSupportTokens: [],
};

export const CHAINS: Record<string, IChain> = {
  ETH: {
    rpcUrl: ETH.RPC,
    rpcUrls: RPC_URLS.ETH,
    chainId: ETH.chainId,
    nativeChainKey: ETH.nativeChainKey,
    minGasGwei: ETH.minGasGwei,
    imageUrl: ETH.imageUrl,
    name: ETH.name,
    symbol: ETH.symbol,
    rangoSymbol: ETH.rangoSymbol,
    chainName: ETH.chainName,
    subName: ETH.subName,
    slug: 'eth',
    networkType: 'mainnet',
    blockExplorerUrl: EXPLORER_URLS.ETH,
    supportedTokenList: GET_RESOURCES_LIST_URL('eth_tokens.json'),
    nativeToken: {
      name: ETH.name,
      address: NATIVE_ADDRESS,
      symbol: ETH.symbol,
      decimals: 18,
      type: ETH.name?.toUpperCase(),
      logoURI: ETH.imageUrl,
    },
    wrappedAddress: '0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2',
    bridgeSupportTokens: ETH.bridgeSupportTokens,
    sendEnable: true,
    receiveEnable: true,
    bridgeEnable: true,
    swapEnable: true,
    importForSetupApp: true,
    importForSetupedApp: true,
  },
  ARB: {
    rpcUrl: ARB.RPC,
    rpcUrls: RPC_URLS.ARB,
    chainId: ARB.chainId,
    nativeChainKey: ARB.nativeChainKey,
    minGasGwei: ARB.minGasGwei,
    imageUrl: ARB.imageUrl,
    name: ARB.name,
    symbol: ARB.symbol,
    rangoSymbol: ARB.rangoSymbol,
    chainName: ARB.chainName,
    subName: ARB.subName,
    slug: 'arb',
    networkType: 'mainnet',
    blockExplorerUrl: EXPLORER_URLS.ARB,
    supportedTokenList: GET_RESOURCES_LIST_URL('arb_tokens.json'),
    // Native gas token on Arbitrum is ETH — ARB is only the governance ERC20
    nativeToken: {
      name: 'Ether',
      symbol: 'ETH',
      address: NATIVE_ADDRESS,
      type: 'NATIVE',
      decimals: 18,
      logoURI:
        'https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/info/logo.png',
    },
    wrappedAddress: '0x82aF49447D8a07e3bd95BD0d56f35241523fBab1',
    bridgeSupportTokens: ARB.bridgeSupportTokens,
    sendEnable: true,
    receiveEnable: true,
    bridgeEnable: true,
    swapEnable: true,
    importForSetupApp: true,
    importForSetupedApp: true,
  },
  POL: {
    rpcUrl: POL.RPC,
    rpcUrls: RPC_URLS.POL,
    chainId: POL.chainId,
    nativeChainKey: POL.nativeChainKey,
    minGasGwei: POL.minGasGwei,
    imageUrl: POL.imageUrl,
    name: POL.name,
    symbol: POL.symbol,
    rangoSymbol: POL.rangoSymbol,
    chainName: POL.chainName,
    subName: POL.subName,
    slug: 'poly',
    networkType: 'mainnet',
    blockExplorerUrl: EXPLORER_URLS.POL,
    supportedTokenList: GET_RESOURCES_LIST_URL('poly_tokens.json'),
    nativeToken: {
      name: POL.name,
      symbol: POL.symbol,
      address: NATIVE_ADDRESS,
      type: POL.name?.toUpperCase(),
      decimals: 18,
      logoURI: POL.imageUrl,
    },
    wrappedAddress: '0x0d500B1d8E8eF31E21C99d1Db9A6444d3ADf1270',
    bridgeSupportTokens: POL.bridgeSupportTokens,
    sendEnable: true,
    receiveEnable: true,
    bridgeEnable: true,
    swapEnable: true,
    importForSetupApp: true,
    importForSetupedApp: true,
  },
  OPT: {
    rpcUrl: OPT.RPC,
    rpcUrls: RPC_URLS.OPT,
    chainId: OPT.chainId,
    nativeChainKey: OPT.nativeChainKey,
    minGasGwei: OPT.minGasGwei,
    imageUrl: OPT.imageUrl,
    name: OPT.name,
    symbol: OPT.symbol,
    rangoSymbol: OPT.rangoSymbol,
    chainName: OPT.chainName,
    subName: OPT.subName,
    slug: 'op',
    networkType: 'mainnet',
    blockExplorerUrl: EXPLORER_URLS.OPT,
    supportedTokenList: GET_RESOURCES_LIST_URL('op_tokens.json'),
    // Native gas token on Optimism is ETH — OP is only the governance ERC20
    nativeToken: {
      name: 'Ether',
      symbol: 'ETH',
      address: NATIVE_ADDRESS,
      type: 'NATIVE',
      decimals: 18,
      logoURI:
        'https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/info/logo.png',
    },
    wrappedAddress: '0x4200000000000000000000000000000000000006',
    bridgeSupportTokens: OPT.bridgeSupportTokens,
    sendEnable: true,
    receiveEnable: true,
    bridgeEnable: true,
    swapEnable: true,
    importForSetupApp: true,
    importForSetupedApp: true,
  },
  AVAX: {
    rpcUrl: AVAX.RPC,
    rpcUrls: RPC_URLS.AVAX,
    chainId: AVAX.chainId,
    nativeChainKey: AVAX.nativeChainKey,
    minGasGwei: AVAX.minGasGwei,
    imageUrl: AVAX.imageUrl,
    name: AVAX.name,
    symbol: AVAX.symbol,
    rangoSymbol: AVAX.rangoSymbol,
    chainName: AVAX.chainName,
    subName: AVAX.subName,
    slug: 'avax',
    networkType: 'mainnet',
    blockExplorerUrl: EXPLORER_URLS.AVAX,
    supportedTokenList: GET_RESOURCES_LIST_URL('avax_tokens.json'),
    nativeToken: {
      name: AVAX.name,
      symbol: AVAX.symbol,
      address: NATIVE_ADDRESS,
      type: AVAX.name?.toUpperCase(),
      decimals: 18,
      logoURI: AVAX.imageUrl,
    },
    wrappedAddress: '0xB31f66AA3C1e785363F0875A1B74E27b85FD66c7',
    bridgeSupportTokens: AVAX.bridgeSupportTokens,
    sendEnable: true,
    receiveEnable: true,
    bridgeEnable: true,
    swapEnable: true,
    importForSetupApp: true,
    importForSetupedApp: true,
  },
  BASE: {
    rpcUrl: BASE.RPC,
    rpcUrls: RPC_URLS.BASE,
    chainId: BASE.chainId,
    nativeChainKey: BASE.nativeChainKey,
    minGasGwei: BASE.minGasGwei,
    imageUrl: BASE.imageUrl,
    name: BASE.name,
    symbol: BASE.symbol,
    rangoSymbol: BASE.rangoSymbol,
    chainName: BASE.chainName,
    subName: BASE.subName,
    slug: 'base',
    networkType: 'mainnet',
    blockExplorerUrl: EXPLORER_URLS.BASE,
    supportedTokenList: GET_RESOURCES_LIST_URL('base_tokens.json'),
    // Native gas token on Base is ETH
    nativeToken: {
      name: 'Ether',
      symbol: 'ETH',
      address: NATIVE_ADDRESS,
      type: 'NATIVE',
      decimals: 18,
      logoURI:
        'https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/info/logo.png',
    },
    wrappedAddress: '0x4200000000000000000000000000000000000006',
    bridgeSupportTokens: BASE.bridgeSupportTokens,
    sendEnable: true,
    receiveEnable: true,
    bridgeEnable: true,
    swapEnable: true,
    importForSetupApp: true,
    importForSetupedApp: true,
  },
  BNB: {
    rpcUrl: BSC.RPC,
    rpcUrls: RPC_URLS.BNB,
    chainId: BSC.chainId,
    nativeChainKey: BSC.nativeChainKey,
    minGasGwei: BSC.minGasGwei,
    imageUrl: BSC.imageUrl,
    name: BSC.name,
    symbol: BSC.symbol,
    rangoSymbol: BSC.rangoSymbol,
    chainName: BSC.chainName,
    subName: BSC.subName,
    slug: 'bsc',
    networkType: 'mainnet',
    blockExplorerUrl: EXPLORER_URLS.BNB,
    supportedTokenList: GET_RESOURCES_LIST_URL('bsc_tokens.json'),
    nativeToken: {
      name: BSC.name,
      symbol: BSC.symbol,
      address: NATIVE_ADDRESS,
      type: BSC.name?.toUpperCase(),
      decimals: 18,
      logoURI: BSC.imageUrl,
    },
    wrappedAddress: '0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c',
    bridgeSupportTokens: BSC.bridgeSupportTokens,
    sendEnable: true,
    receiveEnable: true,
    bridgeEnable: true,
    swapEnable: true,
    importForSetupApp: true,
    importForSetupedApp: true,
  },
  STR: {
    rpcUrl: STR.RPC,
    rpcUrls: RPC_URLS.STR,
    chainId: STR.chainId,
    nativeChainKey: STR.nativeChainKey,
    minGasGwei: STR.minGasGwei,
    imageUrl: STR.imageUrl,
    name: STR.name,
    symbol: STR.symbol,
    chainName: STR.chainName,
    subName: STR.subName,
    slug: 'stellar',
    networkType: 'mainnet',
    blockExplorerUrl: EXPLORER_URLS.STR,
    supportedTokenList: 'https://lobstr.co/api/v1/sep/assets/curated.json',
    nativeToken: {
      name: 'Stellar',
      symbol: 'XLM',
      address: NATIVE_ADDRESS,
      type: STR.name?.toUpperCase(),
      decimals: 7,
      logoURI: STR.imageUrl,
    },
    bridgeSupportTokens: STR.bridgeSupportTokens,
    sendEnable: true,
    receiveEnable: true,
    bridgeEnable: true,
    swapEnable: true,
    importForSetupApp: false,
    importForSetupedApp: true,
  },
  STR_TESTNET: {
    rpcUrl: STR_TESTNET.RPC,
    rpcUrls: RPC_URLS.STR_TESTNET,
    chainId: STR_TESTNET.chainId,
    nativeChainKey: STR_TESTNET.nativeChainKey,
    minGasGwei: STR_TESTNET.minGasGwei,
    imageUrl: STR_TESTNET.imageUrl,
    name: STR_TESTNET.name,
    symbol: STR_TESTNET.symbol,
    chainName: STR_TESTNET.chainName,
    subName: STR_TESTNET.subName,
    slug: 'stellar',
    networkType: 'testnet',
    blockExplorerUrl: EXPLORER_URLS.STR_TESTNET,
    supportedTokenList: GET_STELLAR_TOKEN_LIST_URL('testnet'),
    nativeToken: {
      name: 'Stellar',
      symbol: 'XLM',
      address: NATIVE_ADDRESS,
      type: STR_TESTNET.name?.toUpperCase(),
      decimals: 7,
      logoURI: STR_TESTNET.imageUrl,
    },
    bridgeSupportTokens: STR_TESTNET.bridgeSupportTokens,
    sendEnable: true,
    receiveEnable: true,
    bridgeEnable: true,
    swapEnable: true,
    importForSetupApp: false,
    importForSetupedApp: true,
  },

  // ---------------------------------------------------------------------------
  // EVM Testnets
  // ---------------------------------------------------------------------------

  SEPOLIA: {
    rpcUrl: SEPOLIA.RPC,
    rpcUrls: RPC_URLS.SEPOLIA,
    chainId: SEPOLIA.chainId,
    nativeChainKey: SEPOLIA.nativeChainKey,
    minGasGwei: SEPOLIA.minGasGwei,
    imageUrl: SEPOLIA.imageUrl,
    name: SEPOLIA.name,
    symbol: SEPOLIA.symbol,
    chainName: SEPOLIA.chainName,
    subName: SEPOLIA.subName,
    slug: 'sepolia',
    networkType: 'testnet',
    blockExplorerUrl: EXPLORER_URLS.SEPOLIA,
    supportedTokenList: [],
    nativeToken: {
      name: 'Ether',
      symbol: 'ETH',
      address: NATIVE_ADDRESS,
      type: 'NATIVE',
      decimals: 18,
      logoURI: SEPOLIA.imageUrl,
    },
    wrappedAddress: '0x7b79995e5f793A07Bc00c21412e50Ecae098E7f9',
    bridgeSupportTokens: SEPOLIA.bridgeSupportTokens,
    sendEnable: true,
    receiveEnable: true,
    bridgeEnable: false,
    swapEnable: false,
    importForSetupApp: false,
    importForSetupedApp: false,
  },

  BSC_TESTNET: {
    rpcUrl: BSC_TESTNET_CHAIN.RPC,
    rpcUrls: RPC_URLS.BSC_TESTNET,
    chainId: BSC_TESTNET_CHAIN.chainId,
    nativeChainKey: BSC_TESTNET_CHAIN.nativeChainKey,
    minGasGwei: BSC_TESTNET_CHAIN.minGasGwei,
    imageUrl: BSC_TESTNET_CHAIN.imageUrl,
    name: BSC_TESTNET_CHAIN.name,
    symbol: BSC_TESTNET_CHAIN.symbol,
    chainName: BSC_TESTNET_CHAIN.chainName,
    subName: BSC_TESTNET_CHAIN.subName,
    slug: 'bsc-testnet',
    networkType: 'testnet',
    blockExplorerUrl: EXPLORER_URLS.BSC_TESTNET,
    supportedTokenList: [],
    nativeToken: {
      name: 'BNB',
      symbol: 'BNB',
      address: NATIVE_ADDRESS,
      type: 'NATIVE',
      decimals: 18,
      logoURI: BSC_TESTNET_CHAIN.imageUrl,
    },
    bridgeSupportTokens: BSC_TESTNET_CHAIN.bridgeSupportTokens,
    sendEnable: true,
    receiveEnable: true,
    bridgeEnable: false,
    swapEnable: false,
    importForSetupApp: false,
    importForSetupedApp: false,
  },

  AMOY: {
    rpcUrl: AMOY.RPC,
    rpcUrls: RPC_URLS.AMOY,
    chainId: AMOY.chainId,
    nativeChainKey: AMOY.nativeChainKey,
    minGasGwei: AMOY.minGasGwei,
    imageUrl: AMOY.imageUrl,
    name: AMOY.name,
    symbol: AMOY.symbol,
    chainName: AMOY.chainName,
    subName: AMOY.subName,
    slug: 'amoy',
    networkType: 'testnet',
    blockExplorerUrl: EXPLORER_URLS.AMOY,
    supportedTokenList: [],
    nativeToken: {
      name: 'Polygon',
      symbol: 'POL',
      address: NATIVE_ADDRESS,
      type: 'NATIVE',
      decimals: 18,
      logoURI: AMOY.imageUrl,
    },
    bridgeSupportTokens: AMOY.bridgeSupportTokens,
    sendEnable: true,
    receiveEnable: true,
    bridgeEnable: false,
    swapEnable: false,
    importForSetupApp: false,
    importForSetupedApp: false,
  },

  ARB_SEPOLIA: {
    rpcUrl: ARB_SEPOLIA.RPC,
    rpcUrls: RPC_URLS.ARB_SEPOLIA,
    chainId: ARB_SEPOLIA.chainId,
    nativeChainKey: ARB_SEPOLIA.nativeChainKey,
    minGasGwei: ARB_SEPOLIA.minGasGwei,
    imageUrl: ARB_SEPOLIA.imageUrl,
    name: ARB_SEPOLIA.name,
    symbol: ARB_SEPOLIA.symbol,
    chainName: ARB_SEPOLIA.chainName,
    subName: ARB_SEPOLIA.subName,
    slug: 'arb-sepolia',
    networkType: 'testnet',
    blockExplorerUrl: EXPLORER_URLS.ARB_SEPOLIA,
    supportedTokenList: [],
    nativeToken: {
      name: 'Ether',
      symbol: 'ETH',
      address: NATIVE_ADDRESS,
      type: 'NATIVE',
      decimals: 18,
      logoURI: ARB_SEPOLIA.imageUrl,
    },
    bridgeSupportTokens: ARB_SEPOLIA.bridgeSupportTokens,
    sendEnable: true,
    receiveEnable: true,
    bridgeEnable: false,
    swapEnable: false,
    importForSetupApp: false,
    importForSetupedApp: false,
  },

  OPT_SEPOLIA: {
    rpcUrl: OPT_SEPOLIA.RPC,
    rpcUrls: RPC_URLS.OPT_SEPOLIA,
    chainId: OPT_SEPOLIA.chainId,
    nativeChainKey: OPT_SEPOLIA.nativeChainKey,
    minGasGwei: OPT_SEPOLIA.minGasGwei,
    imageUrl: OPT_SEPOLIA.imageUrl,
    name: OPT_SEPOLIA.name,
    symbol: OPT_SEPOLIA.symbol,
    chainName: OPT_SEPOLIA.chainName,
    subName: OPT_SEPOLIA.subName,
    slug: 'op-sepolia',
    networkType: 'testnet',
    blockExplorerUrl: EXPLORER_URLS.OPT_SEPOLIA,
    supportedTokenList: [],
    nativeToken: {
      name: 'Ether',
      symbol: 'ETH',
      address: NATIVE_ADDRESS,
      type: 'NATIVE',
      decimals: 18,
      logoURI: OPT_SEPOLIA.imageUrl,
    },
    bridgeSupportTokens: OPT_SEPOLIA.bridgeSupportTokens,
    sendEnable: true,
    receiveEnable: true,
    bridgeEnable: false,
    swapEnable: false,
    importForSetupApp: false,
    importForSetupedApp: false,
  },

  BASE_SEPOLIA: {
    rpcUrl: BASE_SEPOLIA.RPC,
    rpcUrls: RPC_URLS.BASE_SEPOLIA,
    chainId: BASE_SEPOLIA.chainId,
    nativeChainKey: BASE_SEPOLIA.nativeChainKey,
    minGasGwei: BASE_SEPOLIA.minGasGwei,
    imageUrl: BASE_SEPOLIA.imageUrl,
    name: BASE_SEPOLIA.name,
    symbol: BASE_SEPOLIA.symbol,
    chainName: BASE_SEPOLIA.chainName,
    subName: BASE_SEPOLIA.subName,
    slug: 'base-sepolia',
    networkType: 'testnet',
    blockExplorerUrl: EXPLORER_URLS.BASE_SEPOLIA,
    supportedTokenList: [],
    nativeToken: {
      name: 'Ether',
      symbol: 'ETH',
      address: NATIVE_ADDRESS,
      type: 'NATIVE',
      decimals: 18,
      logoURI: BASE_SEPOLIA.imageUrl,
    },
    bridgeSupportTokens: BASE_SEPOLIA.bridgeSupportTokens,
    sendEnable: true,
    receiveEnable: true,
    bridgeEnable: false,
    swapEnable: false,
    importForSetupApp: false,
    importForSetupedApp: false,
  },

  AVAX_FUJI: {
    rpcUrl: AVAX_FUJI.RPC,
    rpcUrls: RPC_URLS.AVAX_FUJI,
    chainId: AVAX_FUJI.chainId,
    nativeChainKey: AVAX_FUJI.nativeChainKey,
    minGasGwei: AVAX_FUJI.minGasGwei,
    imageUrl: AVAX_FUJI.imageUrl,
    name: AVAX_FUJI.name,
    symbol: AVAX_FUJI.symbol,
    chainName: AVAX_FUJI.chainName,
    subName: AVAX_FUJI.subName,
    slug: 'avax-fuji',
    networkType: 'testnet',
    blockExplorerUrl: EXPLORER_URLS.AVAX_FUJI,
    supportedTokenList: [],
    nativeToken: {
      name: 'AVAX',
      symbol: 'AVAX',
      address: NATIVE_ADDRESS,
      type: 'NATIVE',
      decimals: 18,
      logoURI: AVAX_FUJI.imageUrl,
    },
    bridgeSupportTokens: AVAX_FUJI.bridgeSupportTokens,
    sendEnable: true,
    receiveEnable: true,
    bridgeEnable: false,
    swapEnable: false,
    importForSetupApp: false,
    importForSetupedApp: false,
  },
};
